[package]
name = "hello_cargo"
version = "0.1.2"
authors = ["hogera<hoge@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.6", features = ["edge"] }
